-- ============================================================================
-- Combined MySQL Initialization Script
-- ============================================================================
-- This file was automatically generated by combining multiple SQL files
-- Generation Date: 2026-02-02 19:34:43
-- ============================================================================


-- ============================================================================
-- File: attendee.sql
-- ============================================================================

DROP DATABASE IF EXISTS attendee;
DROP DATABASE IF EXISTS event;
DROP DATABASE IF EXISTS file;
DROP DATABASE IF EXISTS nacos;
DROP DATABASE IF EXISTS notification;
DROP DATABASE IF EXISTS task;
DROP DATABASE IF EXISTS user;
CREATE DATABASE IF NOT EXISTS attendee;
USE attendee;

create table IF NOT EXISTS event_attendee
(
    id                     bigint auto_increment comment 'Primary key'
        primary key,
    event_id               bigint                             not null comment 'Event ID',
    user_id                bigint                             null comment 'Attendee user ID',
    check_in_token         varchar(64)                        not null comment 'Unique check-in token',
    check_in_status        tinyint  default 0                 null comment 'Check-in status: 0-Not checked in, 1-Checked in',
    check_in_time          datetime                           null comment 'Check-in time',
    qr_code_generated_time datetime                           null comment 'QR code generated time',
    remark                 varchar(500)                       null,
    tenant_id              bigint                             not null comment 'Tenant ID',
    creator                varchar(64)                        null,
    create_time            datetime default CURRENT_TIMESTAMP not null,
    updater                varchar(64)                        null,
    update_time            datetime default CURRENT_TIMESTAMP not null on update CURRENT_TIMESTAMP,
    deleted                bit      default b'0'              not null,
    attendee_email         varchar(255)                       null comment 'Attendee email',
    attendee_name          varchar(100)                       null comment 'Attendee name',
    attendee_mobile        varchar(20)                        null comment 'Attendee mobile phone',
    constraint uk_event_email
        unique (event_id, attendee_email),
    constraint uk_event_user
        unique (event_id, user_id, deleted),
    constraint uk_token
        unique (check_in_token)
)
    comment 'Event Attendee Table';

create index idx_attendee_email
    on event_attendee (attendee_email);

create index idx_event_id
    on event_attendee (event_id);





-- ============================================================================
-- File: event.sql
-- ============================================================================
CREATE DATABASE IF NOT EXISTS event;
USE event;

create table IF NOT EXISTS event
(
    id          bigint               not null
        primary key,
    user_id     bigint               null,
    name        varchar(100)         null,
    description varchar(255)         null,
    status      tinyint(1) default 0 not null comment '0 - Enable; 1 - Disable',
    remark      varchar(200)         null,
    start_time  datetime             null,
    end_time    datetime             null,
    creator     varchar(100)         null,
    create_time datetime             null,
    updater     varchar(100)         null,
    update_time datetime             null,
    deleted     tinyint(1) default 0 not null comment '0 - Normal; 1- Deleted',
    tenant_id   bigint               null,
    location    varchar(255)         null
);

create table IF NOT EXISTS event_participant
(
    id          bigint auto_increment
        primary key,
    event_id    bigint            not null,
    user_id     bigint            not null,
    tenant_id   bigint            not null,
    create_time datetime          not null,
    update_time datetime          not null,
    deleted     tinyint default 0 null,
    creator     bigint            null,
    updater     bigint            null,
    constraint uk_event_user
        unique (event_id, user_id, tenant_id)
);

create table IF NOT EXISTS sys_dept
(
    id           bigint               not null
        primary key,
    name         varchar(100)         null,
    sort         int                  null comment 'Display order (the smaller the value, the higher the priority)',
    lead_user_id bigint               null,
    remark       varchar(200)         null,
    status       tinyint(1) default 0 not null comment '0 - Enable; 1 - Disable',
    creator      varchar(100)         null,
    create_time  datetime             null,
    updater      varchar(100)         null,
    update_time  datetime             null,
    deleted      tinyint(1) default 0 not null comment '0 - Normal; 1- Deleted',
    tenant_id    bigint               null,
    event_id     bigint               null
)
    comment 'Group info table';

create table IF NOT EXISTS sys_user_group
(
    id          bigint auto_increment
        primary key,
    user_id     bigint                                not null comment 'User ID',
    dept_id     bigint                                not null comment 'Group ID',
    event_id    bigint                                not null comment 'Event ID',
    join_time   datetime    default CURRENT_TIMESTAMP null comment 'jion time',
    role_type   int                                   null comment 'role type',
    creator     varchar(64) default ''                null comment 'creator',
    create_time datetime    default CURRENT_TIMESTAMP not null comment 'create time',
    updater     varchar(64) default ''                null comment 'updater',
    update_time datetime    default CURRENT_TIMESTAMP not null on update CURRENT_TIMESTAMP,
    deleted     bit         default b'0'              not null comment 'delete or not',
    tenant_id   bigint      default 0                 not null comment 'tenant id',
    constraint uk_user_event
        unique (user_id, event_id, deleted) comment 'One user in one event only can be in one group'
)
    comment 'User-Group Associated table';

create index idx_dept_id
    on sys_user_group (dept_id);

create index idx_event_id
    on sys_user_group (event_id);





-- ============================================================================
-- File: file.sql
-- ============================================================================

CREATE DATABASE IF NOT EXISTS file;
USE file;

create table IF NOT EXISTS file
(
    id          bigint               not null
        primary key,
    task_log_id bigint               null,
    event_id    bigint               null,
    name        varchar(100)         null,
    object_name varchar(255)         null,
    provider    varchar(50)          null,
    type        varchar(255)         null comment 'Save only file extensions (pdf, jpg, mp4)',
    size        bigint unsigned      null,
    creator     varchar(100)         null,
    create_time datetime             null,
    updater     varchar(100)         null,
    update_time datetime             null,
    deleted     tinyint(1) default 0 not null comment '0 - Normal; 1- Deleted',
    tenant_id   bigint               null
);





-- ============================================================================
-- File: nacos.sql
-- ============================================================================

CREATE DATABASE IF NOT EXISTS nacos;
USE nacos;

create table IF NOT EXISTS config_info
(
    id                 bigint auto_increment comment 'id'
        primary key,
    data_id            varchar(255)                            not null comment 'data_id',
    group_id           varchar(128)                            null comment 'group_id',
    content            longtext                                not null comment 'content',
    md5                varchar(32)                             null comment 'md5',
    gmt_create         datetime      default CURRENT_TIMESTAMP not null comment '创建时间',
    gmt_modified       datetime      default CURRENT_TIMESTAMP not null comment '修改时间',
    src_user           text                                    null comment 'source user',
    src_ip             varchar(50)                             null comment 'source ip',
    app_name           varchar(128)                            null comment 'app_name',
    tenant_id          varchar(128)  default ''                null comment '租户字段',
    c_desc             varchar(256)                            null comment 'configuration description',
    c_use              varchar(64)                             null comment 'configuration usage',
    effect             varchar(64)                             null comment '配置生效的描述',
    type               varchar(64)                             null comment '配置的类型',
    c_schema           text                                    null comment '配置的模式',
    encrypted_data_key varchar(1024) default ''                not null comment '密钥',
    constraint uk_configinfo_datagrouptenant
        unique (data_id, group_id, tenant_id)
)
    comment 'config_info' collate = utf8mb3_bin;

create table IF NOT EXISTS config_info_aggr
(
    id           bigint auto_increment comment 'id'
        primary key,
    data_id      varchar(255)            not null comment 'data_id',
    group_id     varchar(128)            not null comment 'group_id',
    datum_id     varchar(255)            not null comment 'datum_id',
    content      longtext                not null comment '内容',
    gmt_modified datetime                not null comment '修改时间',
    app_name     varchar(128)            null comment 'app_name',
    tenant_id    varchar(128) default '' null comment '租户字段',
    constraint uk_configinfoaggr_datagrouptenantdatum
        unique (data_id, group_id, tenant_id, datum_id)
)
    comment '增加租户字段' collate = utf8mb3_bin;

create table IF NOT EXISTS config_info_beta
(
    id                 bigint auto_increment comment 'id'
        primary key,
    data_id            varchar(255)                            not null comment 'data_id',
    group_id           varchar(128)                            not null comment 'group_id',
    app_name           varchar(128)                            null comment 'app_name',
    content            longtext                                not null comment 'content',
    beta_ips           varchar(1024)                           null comment 'betaIps',
    md5                varchar(32)                             null comment 'md5',
    gmt_create         datetime      default CURRENT_TIMESTAMP not null comment '创建时间',
    gmt_modified       datetime      default CURRENT_TIMESTAMP not null comment '修改时间',
    src_user           text                                    null comment 'source user',
    src_ip             varchar(50)                             null comment 'source ip',
    tenant_id          varchar(128)  default ''                null comment '租户字段',
    encrypted_data_key varchar(1024) default ''                not null comment '密钥',
    constraint uk_configinfobeta_datagrouptenant
        unique (data_id, group_id, tenant_id)
)
    comment 'config_info_beta' collate = utf8mb3_bin;

create table IF NOT EXISTS config_info_tag
(
    id           bigint auto_increment comment 'id'
        primary key,
    data_id      varchar(255)                           not null comment 'data_id',
    group_id     varchar(128)                           not null comment 'group_id',
    tenant_id    varchar(128) default ''                null comment 'tenant_id',
    tag_id       varchar(128)                           not null comment 'tag_id',
    app_name     varchar(128)                           null comment 'app_name',
    content      longtext                               not null comment 'content',
    md5          varchar(32)                            null comment 'md5',
    gmt_create   datetime     default CURRENT_TIMESTAMP not null comment '创建时间',
    gmt_modified datetime     default CURRENT_TIMESTAMP not null comment '修改时间',
    src_user     text                                   null comment 'source user',
    src_ip       varchar(50)                            null comment 'source ip',
    constraint uk_configinfotag_datagrouptenanttag
        unique (data_id, group_id, tenant_id, tag_id)
)
    comment 'config_info_tag' collate = utf8mb3_bin;

create table IF NOT EXISTS config_tags_relation
(
    id        bigint                  not null comment 'id',
    tag_name  varchar(128)            not null comment 'tag_name',
    tag_type  varchar(64)             null comment 'tag_type',
    data_id   varchar(255)            not null comment 'data_id',
    group_id  varchar(128)            not null comment 'group_id',
    tenant_id varchar(128) default '' null comment 'tenant_id',
    nid       bigint auto_increment comment 'nid, 自增长标识'
        primary key,
    constraint uk_configtagrelation_configidtag
        unique (id, tag_name, tag_type)
)
    comment 'config_tag_relation' collate = utf8mb3_bin;

create index idx_tenant_id
    on config_tags_relation (tenant_id);

create table IF NOT EXISTS group_capacity
(
    id                bigint unsigned auto_increment comment '主键ID'
        primary key,
    group_id          varchar(128) default ''                not null comment 'Group ID，空字符表示整个集群',
    quota             int unsigned default '0'               not null comment '配额，0表示使用默认值',
    `usage`           int unsigned default '0'               not null comment '使用量',
    max_size          int unsigned default '0'               not null comment '单个配置大小上限，单位为字节，0表示使用默认值',
    max_aggr_count    int unsigned default '0'               not null comment '聚合子配置最大个数，，0表示使用默认值',
    max_aggr_size     int unsigned default '0'               not null comment '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值',
    max_history_count int unsigned default '0'               not null comment '最大变更历史数量',
    gmt_create        datetime     default CURRENT_TIMESTAMP not null comment '创建时间',
    gmt_modified      datetime     default CURRENT_TIMESTAMP not null comment '修改时间',
    constraint uk_group_id
        unique (group_id)
)
    comment '集群、各Group容量信息表' collate = utf8mb3_bin;

create table IF NOT EXISTS his_config_info
(
    id                 bigint unsigned                         not null comment 'id',
    nid                bigint unsigned auto_increment comment 'nid, 自增标识'
        primary key,
    data_id            varchar(255)                            not null comment 'data_id',
    group_id           varchar(128)                            not null comment 'group_id',
    app_name           varchar(128)                            null comment 'app_name',
    content            longtext                                not null comment 'content',
    md5                varchar(32)                             null comment 'md5',
    gmt_create         datetime      default CURRENT_TIMESTAMP not null comment '创建时间',
    gmt_modified       datetime      default CURRENT_TIMESTAMP not null comment '修改时间',
    src_user           text                                    null comment 'source user',
    src_ip             varchar(50)                             null comment 'source ip',
    op_type            char(10)                                null comment 'operation type',
    tenant_id          varchar(128)  default ''                null comment '租户字段',
    encrypted_data_key varchar(1024) default ''                not null comment '密钥'
)
    comment '多租户改造' collate = utf8mb3_bin;

create index idx_did
    on his_config_info (data_id);

create index idx_gmt_create
    on his_config_info (gmt_create);

create index idx_gmt_modified
    on his_config_info (gmt_modified);

create table IF NOT EXISTS permissions
(
    role     varchar(50)  not null comment 'role',
    resource varchar(128) not null comment 'resource',
    action   varchar(8)   not null comment 'action',
    constraint uk_role_permission
        unique (role, resource, action)
);

create table IF NOT EXISTS roles
(
    username varchar(50) not null comment 'username',
    role     varchar(50) not null comment 'role',
    constraint idx_user_role
        unique (username, role)
);

create table IF NOT EXISTS tenant_capacity
(
    id                bigint unsigned auto_increment comment '主键ID'
        primary key,
    tenant_id         varchar(128) default ''                not null comment 'Tenant ID',
    quota             int unsigned default '0'               not null comment '配额，0表示使用默认值',
    `usage`           int unsigned default '0'               not null comment '使用量',
    max_size          int unsigned default '0'               not null comment '单个配置大小上限，单位为字节，0表示使用默认值',
    max_aggr_count    int unsigned default '0'               not null comment '聚合子配置最大个数',
    max_aggr_size     int unsigned default '0'               not null comment '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值',
    max_history_count int unsigned default '0'               not null comment '最大变更历史数量',
    gmt_create        datetime     default CURRENT_TIMESTAMP not null comment '创建时间',
    gmt_modified      datetime     default CURRENT_TIMESTAMP not null comment '修改时间',
    constraint uk_tenant_id
        unique (tenant_id)
)
    comment '租户容量信息表' collate = utf8mb3_bin;

create table IF NOT EXISTS tenant_info
(
    id            bigint auto_increment comment 'id'
        primary key,
    kp            varchar(128)            not null comment 'kp',
    tenant_id     varchar(128) default '' null comment 'tenant_id',
    tenant_name   varchar(128) default '' null comment 'tenant_name',
    tenant_desc   varchar(256)            null comment 'tenant_desc',
    create_source varchar(32)             null comment 'create_source',
    gmt_create    bigint                  not null comment '创建时间',
    gmt_modified  bigint                  not null comment '修改时间',
    constraint uk_tenant_info_kptenantid
        unique (kp, tenant_id)
)
    comment 'tenant_info' collate = utf8mb3_bin;

create index idx_tenant_id
    on tenant_info (tenant_id);

create table IF NOT EXISTS users
(
    username varchar(50)  not null comment 'username'
        primary key,
    password varchar(500) not null comment 'password',
    enabled  tinyint(1)   not null comment 'enabled'
);
INSERT INTO users (username, password, enabled)
VALUES ('nacos', '$2a$10$EuWPZHzz32dJN7jexM34MOeYirDdFAZm2kuWj7VEOJhhZkDrxfvUu', TRUE);

INSERT INTO roles (username, role)
VALUES ('nacos', 'ROLE_ADMIN');




-- ============================================================================
-- File: notification.sql
-- ============================================================================

CREATE DATABASE IF NOT EXISTS notification;
USE notification;

create table notification_delivery
(
    id            varchar(36)                                                                       not null
        primary key,
    created_at    datetime(6)                                                                       not null,
    updated_at    datetime(6)                                                                       null,
    channel       enum ('EMAIL', 'PUSH', 'WS')                                                      not null,
    event_id      varchar(120)                                                                      not null,
    recipient_key varchar(160)                                                                      not null,
    status        enum ('CREATED', 'DELIVERED', 'FAILED')                                           not null,
    type          enum ('ATTENDEE_INVITE', 'MEMBER_INVITE', 'NEW_TASK_ASSIGN', 'ORGANIZER_WELCOME') not null,
    constraint uk_event_channel_recipient
        unique (event_id, channel, recipient_key)
);

create table email_message
(
    delivery_id         varchar(36)                        not null
        primary key,
    created_at          datetime(6)                        not null,
    updated_at          datetime(6)                        null,
    error_message       tinytext                           null,
    provider            enum ('AWS_SES')                   not null,
    provider_message_id varchar(200)                       null,
    status              enum ('FAILED', 'PENDING', 'SENT') not null,
    constraint fk_email_delivery
        foreign key (delivery_id) references notification_delivery (id)
);

create index idx_recipient_created
    on notification_delivery (recipient_key asc, created_at desc);

create table notification_device
(
    id         varchar(36)                           not null
        primary key,
    created_at datetime(6)                           not null,
    updated_at datetime(6)                           null,
    platform   enum ('ANDROID', 'IOS', 'WEB')        not null,
    status     enum ('ACTIVE', 'INVALID', 'REVOKED') not null,
    token      varchar(1024)                         not null,
    user_id    varchar(64)                           not null
);

create index idx_device_user_status
    on notification_device (user_id, status);

create table push_message
(
    delivery_id   varchar(36)                        not null
        primary key,
    created_at    datetime(6)                        not null,
    updated_at    datetime(6)                        null,
    error_message longtext                           null,
    fcm_id        varchar(200)                       null,
    status        enum ('FAILED', 'PENDING', 'SENT') not null,
    token         varchar(512)                       null,
    constraint fk_push_delivery
        foreign key (delivery_id) references notification_delivery (id)
);





-- ============================================================================
-- File: task.sql
-- ============================================================================

CREATE DATABASE IF NOT EXISTS task;
USE task;

create table IF NOT EXISTS task
(
    id          bigint               not null
        primary key,
    user_id     bigint               null,
    event_id    bigint               null,
    name        varchar(100)         null,
    description varchar(255)         null,
    status      tinyint(1) default 0 not null comment '0 - Enable; 1 - Disable',
    remark      varchar(200)         null,
    start_time  datetime             null,
    end_time    datetime             null,
    creator     varchar(100)         null,
    create_time datetime             null,
    updater     varchar(100)         null,
    update_time datetime             null,
    deleted     tinyint(1) default 0 not null comment '0 - Normal; 1- Deleted',
    tenant_id   bigint               null
);

create table IF NOT EXISTS task_log
(
    id             bigint               not null
        primary key,
    task_id        bigint               null,
    action         int                  null comment 'Operation actions
CREATE
UPDATE
PAUSE
CANCEL
COMPLETE
ASSIGN',
    target_user_id bigint               null,
    money_cost     decimal(10, 2)       null comment 'Monetary cost (amount, unit: yuan/US dollars, etc., in the system''s unified currency)',
    labor_hour     decimal(10, 2)       null comment 'Manpower input hours (hours, can be decimal, such as 1.5 hours)',
    remark         varchar(200)         null,
    creator        varchar(100)         null,
    create_time    datetime             null,
    updater        varchar(100)         null,
    update_time    datetime             null,
    deleted        tinyint(1) default 0 not null comment '0 - Normal; 1- Deleted',
    tenant_id      bigint               null
);





-- ============================================================================
-- File: user.sql
-- ============================================================================

CREATE DATABASE IF NOT EXISTS user;
USE user;

create table IF NOT EXISTS sys_dict_data
(
    id          int                  not null
        primary key,
    dict_type   varchar(100)         null,
    sort        int                  null comment 'Display order (the smaller the value, the higher the priority)',
    label       varchar(100)         null comment 'Text displayed to the user (such as "Enable", "Disable")',
    value       varchar(100)         null comment 'The actual stored value (such as "0", "1" or English code)',
    status      tinyint(1) default 0 not null comment '0 - Enable; 1 - Disable',
    remark      varchar(200)         null,
    creator     varchar(100)         null,
    create_time datetime             null,
    updater     varchar(100)         null,
    update_time datetime             null,
    deleted     tinyint(1) default 0 not null comment '0 - Normal; 1- Deleted'
);

create table IF NOT EXISTS sys_dict_type
(
    id          bigint               not null
        primary key,
    name        varchar(100)         null,
    type        int                  null,
    status      tinyint(1) default 0 not null comment '0 - Enable; 1 - Disable',
    remark      varchar(200)         null,
    creator     varchar(100)         null,
    create_time datetime             null,
    updater     varchar(100)         null,
    update_time datetime             null,
    deleted     tinyint(1) default 0 not null comment '0 - Normal; 1- Deleted'
);

create table IF NOT EXISTS sys_permission
(
    id             bigint                       not null
        primary key,
    name           varchar(100)                 null,
    permission_key varchar(50)                  null,
    description    varchar(100)                 null,
    type           tinyint                      null comment '1-menu 2-button 3-API',
    parent_id      bigint                       null comment 'To store parent permission id',
    status         tinyint    default 0         null comment '0-Enable 1- Disable',
    creator        varchar(100)                 null,
    create_time    datetime                     null,
    updater        varchar(100) charset utf8mb3 null,
    update_time    datetime                     null,
    deleted        tinyint(1) default 0         null,
    tenant_id      bigint                       null
);

create table IF NOT EXISTS sys_post
(
    id          bigint               not null
        primary key,
    name        varchar(100)         null,
    sort        int                  null comment 'Display order (the smaller the value, the higher the priority)',
    status      tinyint(1) default 0 not null comment '0 - Enable; 1 - Disable',
    remark      varchar(200)         null,
    creator     varchar(100)         null,
    create_time datetime             null,
    updater     varchar(100)         null,
    update_time datetime             null,
    deleted     tinyint(1) default 0 not null comment '0 - Normal; 1- Deleted',
    tenant_id   bigint               null
)
    comment 'Position info table';

create table IF NOT EXISTS sys_role
(
    id              bigint               not null
        primary key,
    name            varchar(100)         null,
    role_key        varchar(50)          null,
    status          tinyint(1) default 0 not null comment '0 - Enable; 1 - Disable',
    permission_list json                 null,
    remark          varchar(200)         null,
    creator         varchar(100)         null,
    create_time     datetime             null,
    updater         varchar(100)         null,
    update_time     datetime             null,
    deleted         tinyint(1) default 0 not null comment '0 - Normal; 1- Deleted',
    tenant_id       bigint               null
);

create table IF NOT EXISTS sys_role_permission
(
    id            bigint                       not null
        primary key,
    role_id       bigint                       null,
    permission_id bigint                       null,
    creator       varchar(100)                 null,
    create_time   datetime                     null,
    updater       varchar(100) charset utf8mb3 null,
    update_time   datetime                     null,
    deleted       tinyint(1) default 0         null,
    tenant_id     bigint                       null
);

create table IF NOT EXISTS sys_tenant
(
    id              bigint               not null comment 'Primary key'
        primary key,
    name            varchar(100)         null comment 'Organization name',
    contact_user_id bigint               null comment 'Store sys_user table primary key',
    contact_name    varchar(100)         null comment 'Contact person''s name',
    contact_mobile  varchar(20)          null comment 'Contact person''s mobile',
    address         varchar(500)         null,
    status          tinyint(1) default 0 not null comment '0 - Enable; 1 - Disable',
    tenant_code     varchar(20)          null comment 'User can use this code to join organization',
    creator         varchar(100)         null,
    create_time     datetime             null,
    updater         varchar(100)         null,
    update_time     datetime             null,
    deleted         tinyint(1) default 0 not null comment '0 - Normal; 1 - Deleted'
)
    comment 'Tenant (Organization) table';

create table IF NOT EXISTS sys_user
(
    id          bigint auto_increment comment 'Primary Key'
        primary key,
    username    varchar(100)                 null,
    password    varchar(100)                 null,
    remark      varchar(200)                 null,
    email       varchar(200)                 null,
    phone       varchar(20)                  null,
    status      tinyint(1) default 0         not null comment '0 - Enable; 1 - Disable',
    login_time  datetime                     null comment 'The latest login datetime',
    dept_id     bigint                       null,
    post_list   json                         null,
    creator     varchar(100) charset utf8mb3 null,
    create_time datetime                     null,
    updater     varchar(100) charset utf8mb3 null,
    update_time datetime                     null,
    deleted     tinyint(1) default 0         not null comment '0 - Normal; 1- Deleted',
    tenant_id   bigint                       null,
    constraint username_unique_key
        unique (username)
)
    comment 'User info table';

create table IF NOT EXISTS sys_user_post
(
    id          bigint               not null
        primary key,
    user_id     bigint               null,
    post_id     bigint               null,
    creator     varchar(100)         null,
    create_time datetime             null,
    updater     varchar(100)         null,
    update_time datetime             null,
    deleted     tinyint(1) default 0 not null comment '0 - Normal; 1- Deleted',
    tenant_id   bigint               null
);

create table IF NOT EXISTS sys_user_role
(
    id          bigint                       not null
        primary key,
    user_id     bigint                       null,
    role_id     bigint                       null,
    creator     varchar(100)                 null,
    create_time datetime                     null,
    updater     varchar(100) charset utf8mb3 null,
    update_time datetime                     null,
    deleted     tinyint(1) default 0         null,
    tenant_id   bigint                       null
);

# Permissions
INSERT INTO user.sys_permission (id, name, permission_key, description, type, parent_id, status, creator, create_time, updater, update_time, deleted, tenant_id) VALUES (1971465366969307138, 'All permission', '*', null, 3, null, 0, null, null, null, null, 0, null);
INSERT INTO user.sys_permission (id, name, permission_key, description, type, parent_id, status, creator, create_time, updater, update_time, deleted, tenant_id) VALUES (1971465366969307139, 'Create member', 'system:organizer:member:create', null, 3, null, 0, null, null, null, null, 0, null);
INSERT INTO user.sys_permission (id, name, permission_key, description, type, parent_id, status, creator, create_time, updater, update_time, deleted, tenant_id) VALUES (1971465366969307140, 'Update member', 'system:organizer:member:update', null, 3, null, 0, null, null, null, null, 0, null);
INSERT INTO user.sys_permission (id, name, permission_key, description, type, parent_id, status, creator, create_time, updater, update_time, deleted, tenant_id) VALUES (1971465366969307141, 'Delete member', 'system:organizer:member:delete', null, 3, null, 0, null, null, null, null, 0, null);
INSERT INTO user.sys_permission (id, name, permission_key, description, type, parent_id, status, creator, create_time, updater, update_time, deleted, tenant_id) VALUES (1971465366969307142, 'Restore member', 'system:organizer:member:restore', null, 3, null, 0, null, null, null, null, 0, null);
INSERT INTO user.sys_permission (id, name, permission_key, description, type, parent_id, status, creator, create_time, updater, update_time, deleted, tenant_id) VALUES (1971465366969307143, 'Disable member', 'system:organizer:member:disable', null, 3, null, 0, null, null, null, null, 0, null);
INSERT INTO user.sys_permission (id, name, permission_key, description, type, parent_id, status, creator, create_time, updater, update_time, deleted, tenant_id) VALUES (1971465366969307144, 'Enable member', 'system:organizer:member:enable', null, 3, null, 0, null, null, null, null, 0, null);
INSERT INTO user.sys_permission (id, name, permission_key, description, type, parent_id, status, creator, create_time, updater, update_time, deleted, tenant_id) VALUES (1971465366969307145, 'Query member', 'system:organizer:member:query', null, 3, null, 0, null, null, null, null, 0, null);
INSERT INTO user.sys_permission (id, name, permission_key, description, type, parent_id, status, creator, create_time, updater, update_time, deleted, tenant_id) VALUES (1971465366969307147, 'All system permission', 'system:*', null, 3, null, 0, null, null, null, null, 0, null);
INSERT INTO user.sys_permission (id, name, permission_key, description, type, parent_id, status, creator, create_time, updater, update_time, deleted, tenant_id) VALUES (1972530048253644801, 'Create role', 'system:role:role:create', '', 3, null, 0, '1', '2025-09-29 13:13:06', '1', '2025-09-29 13:13:06', 0, null);
INSERT INTO user.sys_permission (id, name, permission_key, description, type, parent_id, status, creator, create_time, updater, update_time, deleted, tenant_id) VALUES (1972530312687734786, 'Update role', 'system:role:role:update', '', 3, null, 0, '1', '2025-09-29 13:14:09', '1', '2025-09-29 13:14:09', 0, null);
INSERT INTO user.sys_permission (id, name, permission_key, description, type, parent_id, status, creator, create_time, updater, update_time, deleted, tenant_id) VALUES (1972530368878825473, 'Delete role', 'system:role:role:delete', '', 3, null, 0, '1', '2025-09-29 13:14:22', '1', '2025-09-29 13:14:22', 0, null);
INSERT INTO user.sys_permission (id, name, permission_key, description, type, parent_id, status, creator, create_time, updater, update_time, deleted, tenant_id) VALUES (1972530416639365122, 'Query role', 'system:role:role:query', '', 3, null, 0, '1', '2025-09-29 13:14:34', '1', '2025-09-29 13:14:34', 0, null);
INSERT INTO user.sys_permission (id, name, permission_key, description, type, parent_id, status, creator, create_time, updater, update_time, deleted, tenant_id) VALUES (1972530460977352706, 'Assign role', 'system:role:role:assign', '', 3, null, 0, '1', '2025-09-29 13:14:44', '1', '2025-09-29 13:14:44', 0, null);
INSERT INTO user.sys_permission (id, name, permission_key, description, type, parent_id, status, creator, create_time, updater, update_time, deleted, tenant_id) VALUES (1972530560973754370, 'Create event', 'system:event:event:create', '', 3, null, 0, '1', '2025-09-29 13:15:08', '1', '2025-09-29 13:15:08', 0, null);
INSERT INTO user.sys_permission (id, name, permission_key, description, type, parent_id, status, creator, create_time, updater, update_time, deleted, tenant_id) VALUES (1972530615646507010, 'Update event', 'system:event:event:update', '', 3, null, 0, '1', '2025-09-29 13:15:21', '1', '2025-09-29 13:15:21', 0, null);
INSERT INTO user.sys_permission (id, name, permission_key, description, type, parent_id, status, creator, create_time, updater, update_time, deleted, tenant_id) VALUES (1972530679114715138, 'Delete event', 'system:event:event:delete', '', 3, null, 0, '1', '2025-09-29 13:15:36', '1', '2025-09-29 13:15:36', 0, null);
INSERT INTO user.sys_permission (id, name, permission_key, description, type, parent_id, status, creator, create_time, updater, update_time, deleted, tenant_id) VALUES (1972530723331067905, 'Query event', 'system:event:event:query', '', 3, null, 0, '1', '2025-09-29 13:15:47', '1', '2025-09-29 13:15:47', 0, null);
INSERT INTO user.sys_permission (id, name, permission_key, description, type, parent_id, status, creator, create_time, updater, update_time, deleted, tenant_id) VALUES (1972530831342784513, 'Create task', 'system:event:task:create', '', 3, null, 0, '1', '2025-09-29 13:16:13', '1', '2025-09-29 13:16:13', 0, null);
INSERT INTO user.sys_permission (id, name, permission_key, description, type, parent_id, status, creator, create_time, updater, update_time, deleted, tenant_id) VALUES (1972530892776755202, 'Update task', 'system:event:task:update', '', 3, null, 0, '1', '2025-09-29 13:16:27', '1', '2025-09-29 13:16:27', 0, null);
INSERT INTO user.sys_permission (id, name, permission_key, description, type, parent_id, status, creator, create_time, updater, update_time, deleted, tenant_id) VALUES (1972530937144102913, 'Delete task', 'system:event:task:delete', '', 3, null, 0, '1', '2025-09-29 13:16:38', '1', '2025-09-29 13:16:38', 0, null);
INSERT INTO user.sys_permission (id, name, permission_key, description, type, parent_id, status, creator, create_time, updater, update_time, deleted, tenant_id) VALUES (1972530991993016322, 'Query task', 'system:event:task:query', '', 3, null, 0, '1', '2025-09-29 13:16:51', '1', '2025-09-29 13:16:51', 0, null);
INSERT INTO user.sys_permission (id, name, permission_key, description, type, parent_id, status, creator, create_time, updater, update_time, deleted, tenant_id) VALUES (1972531040659525634, 'Assign task', 'system:event:task:assign', '', 3, null, 0, '1', '2025-09-29 13:17:03', '1', '2025-09-29 13:17:03', 0, null);

