apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway-sa
  namespace: chronoflow
  labels:
    app: gateway
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-service-sa
  namespace: chronoflow
  labels:
    app: user-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: event-service-sa
  namespace: chronoflow
  labels:
    app: event-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: task-service-sa
  namespace: chronoflow
  labels:
    app: task-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: attendee-service-sa
  namespace: chronoflow
  labels:
    app: attendee-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: file-service-sa
  namespace: chronoflow
  labels:
    app: file-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service-sa
  namespace: chronoflow
  labels:
    app: notification-service
