apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: chronoflow
  labels:
    app: mongodb
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongodb
  selector:
    app: mongodb
