apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: chronoflow
  labels:
    app: user-service
    version: v1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
        version: v1
    spec:
      tolerations:
        - key: "node.gke.io/balloon-pod-resize"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: user-service
          image: shchow/user-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          env:
            - name: PROD_MASTER_DB_HOST
              value: "mysql.chronoflow.svc.cluster.local"
            - name: PROD_MASTER_DB_PORT
              value: "3306"
            - name: PROD_MASTER_DB_USER
              value: "root"
            - name: PROD_MASTER_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: root-password
            - name: PROD_SLAVE_DB_HOST
              value: "mysql.chronoflow.svc.cluster.local"
            - name: PROD_SLAVE_DB_PORT
              value: "3306"
            - name: PROD_SLAVE_DB_USER
              value: "root"
            - name: PROD_SLAVE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: root-password
            - name: PROD_REDIS_HOST
              value: "redis.chronoflow.svc.cluster.local"
            - name: PROD_REDIS_PORT
              value: "6379"
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: JAVA_OPTS
              value: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/./urandom"
            - name: SERVER_PORT
              value: "8081"
            - name: NACOS_HOST
              value: "nacos.chronoflow.svc.cluster.local"
            - name: NACOS_PORT
              value: "8848"
            - name: NACOS_USERNAME
              value: "nacos"
            - name: NACOS_PASSWORD
              value: "nacos"
            - name: PUB_SUB_SERVICE_ACCOUNT_JSON
              valueFrom:
                secretKeyRef:
                  name: pub-sub
                  key: pub-sub-service-account
            - name: GCP_PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: noti-config
                  key: gcp.project.id
            - name: FIREBASE_SERVICE_ACCOUNT_JSON
              valueFrom:
                secretKeyRef:
                  name: firebase
                  key: account-json
            - name: MOBILE_SSO_JWKS
              value: https://www.googleapis.com/oauth2/v3/certs
            - name: MOBILE_CLIENT_ID
              value: 344291036721-79prbg72kl8q5lac22kmol4arh39r5vg.apps.googleusercontent.com
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "800Mi"
              cpu: "400m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 240
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 240
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
      restartPolicy: Always
      terminationGracePeriodSeconds: 30