# GSM secret ids: FIREBASE_SERVICE_ACCOUNT_JSON, MOBILE_CLIENT_ID
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: firebase-from-gcp-sm
  namespace: chronoflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: firebase
    creationPolicy: Owner
  data:
    - secretKey: account-json
      remoteRef:
        key: FIREBASE_SERVICE_ACCOUNT_JSON
    - secretKey: mobile-client-id
      remoteRef:
        key: MOBILE_CLIENT_ID
