# GSM secret id for user-service Firebase service account JSON
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: firebase-auth-from-gcp-sm
  namespace: chronoflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: firebase-auth
    creationPolicy: Owner
  data:
    - secretKey: account-json
      remoteRef:
        key: BASE64_AUTH_FIREBASE_SERVICE_ACCOUNT_JSON
